version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: e-commerce
    restart: always

volumes:
  postgres_data: